apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: task-manager
spec:
  selector:
    app: client
  type: NodePort
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
      nodePort: 30000
