apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: task-manager
spec:
  selector:
    matchLabels:
      app: client
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: react-client:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
          ports:
            - containerPort: 5173
