services:
  spring-replica-1:
    image: spring-server:latest
    ports:
      - "8081:8080"
    networks:
      - app-network

  spring-replica-2:
    image: spring-server:latest
    ports:
      - "8082:8080"
    networks:
      - app-network

  spring-replica-3:
    image: spring-server:latest
    ports:
      - "8083:8080"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  react-client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: dev
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://nginx
    restart: always
    networks:
      - app-network

networks:
  app-network:
