apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
  namespace: task-manager
spec:
  selector:
    matchLabels:
      app: proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: spring-proxy:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
          ports:
            - containerPort: 8080
