apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: task-manager
spec:
  selector:
    app: server
  type: NodePort
  ports:
    - protocol: TCP
      port: 30303
      targetPort: 30303
      nodePort: 30303
