apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: task-manager
spec:
  selector:
    matchLabels:
      app: server
  replicas: 3
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: spring-server:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: "512Mi"
              cpu: "0.5"
          env:
            - name: SERVER_PORT
              value: "30303"
          ports:
            - containerPort: 30303
